schemes/The Hulk.itermcolors
Issue #37 #38 @sunaku mentioned this about extra keys in the itermcolor
files. Bug was not setting colors in iterm2; compared
with working color theme files and removed extra's in here. Seems to be
working so far.
=> The Hulk now working in iterm2 for OS X.

schemes/Material.itermcolors, schemes/MaterialDark.itermcolors
I had an issue with Material schemes (light and dark), which were silently failing during preset load. This fix replaces files with their "stable" versions, as they are named by stoeffel, theme author. [Source]  (https://github.com/stoeffel/material-iterm) remains the same as in project credits.
=> Fix Material scheme.

schemes/Brogrammer.itermcolors
In iTerm2 Brogrammer theme could be imported, but when selected, it failed silently. This fix is updated version from the same source as mentioned in credits, [bahlo](https://github.com/bahlo/iterm-colors).
=> fix brogrammer by updating from source

README.md, terminator/Parasio Dark.config
There was a typo in Paraiso Dark color scheme name. This pull request fixes it and removes duplicated style also.
=> Fix typos problems

tools/update_all.py, tools/xrdb2konsole.py, tools/xrdb2putty.py, tools/xrdb2terminator.py, tools/xrdb2xfce_terminal.py
Create basic `main(xrdb_path, output_path=None)` interface to all python modules, so they can be imported by `update_all.py` instead of using subprocess.
- Added `xrdb2Xresources` conversion into `update_all.py`
- Added `xrdb2xfce_terminal` conversion into `update_all.py`
=> Update python modules interfaces, improve update_all.py

tools/genHTML
In efforts to try and make it easier to keep gh-pages up to date, here's a small ruby script that will generate an html snippet for you, which can be easily copy-pasted into the index.html file.
```
tools/genHTML | pbcopy
```
* No dependencies, just any ruby
* Knows how to map screenshot names to scheme names
- Uses naive filename conversion on most files
- Uses Levenshtein distance (with min threshold) on remaining files
* URL-encodes all names
* Outputs HTML into stdout
* Links scheme names to raw scheme file (Can be easily removed if this isn't desirable)
* Skips any screenshot that do not match a scheme name by 10 or more Lev. distance (currently only `solarized_darcula_with_background`)
* We could reuse this script's ability to auto-associate screenshots and schemes for generating …
=> Add a script for generating HTML screenshot list

termite/OneHalfDark, termite/OneHalfLight
The Xorg logs error when there're double quotes in the termite configs
=> Fix OneHalfDark and OneHalfLight termite configs

README.md
Add instructions for Windows Terminal and correct some typos in README.md
=> Correct and add content to README

schemes/Sakura.itermcolors
There was a rogue character at the beginning of sakura.itemcolors that was causing iTerm2 to throw an error when trying to import it. I am unsure if this problem exists elsewhere.
=> removed erroneous character from Sakura.itermcolors

tools/windowsterminalinstaller.ps1, windowsterminal/install.ps1
- Loads existing profiles.json
- Only installs color schemes in windows terminal directory not already installed
- Writes profiles.json back out with updates
=> Add install script for windows terminal profile

README.md
Add links to installation instructions to match other supported terminals.
Note: I had to rename the Visual Studio Code entry as "(vscode)" breaks the markdown links as they are specified using parens.
=> Link to vscode / windows terminal docs

README.md, tools/import-scheme.sh
The script can import all color schemes at once, or import only a few color schemes.
=> Add bash script to import color schemes for iTerm

tools/windowsterminal2vscode.ps1
Fix the vscode generation script with the missing comma
The vscode schemes themselves were fixed in https://github.com/mbadolato/iTerm2-Color-Schemes/pull/281
=> Add missing comma in vscode script

tools/update_all.py, tools/xrdb2vscode.py
There is an existing Powershell script that does this, but I updated the Python script (which was actually a copy of the Windows Terminal converter) so as to be easily callable from `update_all.py`. Closes #307
=> Convert xrdb to VS Code format

tools/iterm2chromessh.py
Reads from the .itermcolors file and convert to Ansi Colors + Other color format in Hex.
The Ansi color scheme can be pasted to Chrome Secure Shell config field directly.
=> Add Chrome Secure Shell palette hex color conversion

alacritty/GitHub Dark.yml, alacritty/darkermatrix.yml, alacritty/darkmatrix.yml, alacritty/matrix.yml, putty/GitHub Dark.reg, remmina/GitHub Dark.colors, schemes/GitHub Dark.itermcolors, vscode/darkermatrix.json, vscode/darkmatrix.json, vscode/matrix.json, wezterm/GitHub Dark.toml, xrdb/GitHub Dark.xrdb
Fix cursortext color in GitHub Dark
=> fix: GitHub Dark cursortext was white on light gray

index.html
The previous URL's last component was `Ayu+Mirage.itermcolors`. After manually browsing to the raw color profile ourselves we found that last component was `Ayu%20Mirage.itermcolors` instead.
We have just updated the `href` attribute of the corresponding `<a>` tag so that it points to the URL we're actually seeing when navigating to the raw color scheme.
This PR tries to solve issue #378.
=> Fix link for Ayu Mirage color profile

tools/genHTML
This will escape URIs for use in HTML rather than for use in server side calls.  This resolves issue #389.
Switching from CGI to Addressable::URI will more effectively encode characters for use in client side URLs.
New links were tested in existing index.html file in the gh-pages branch and the links all appear to work in spot checks.
=> Escape URIs using Addressable::URI instead of CGI

tools/preview.rb
When previewing color schemes,` tools/preview.rb schemes/*`, the name of the each scheme is printed.  As the schemes are reviewed the list of names starts to wrap and scrolls the sample text off the screen.  
My pull request keeps the names of the schemes on the same line on the screen so that the screen does not scroll.
IMHO, this makes previewing the color schemes with some sample text much better.
=> print scheme names on same line during preview

screenshots/README.md, tools/generate_screenshots_readme.py
I seem to be a freak as I prefer light themes.
Maybe others also want to see just light themes, or maybe only dark ones?
So I changed generate_screenshots_readme.py to
1. Sort the screenshots by brightness of the background color
2. Use the theme names instead of the screenshot name in the screenshots "headline"
=> Categorized screenshots

Dockerfile, README.md, generate-all.sh
It's not required to have pyenv in the docker container.
Additionally `pip install --upgrade pip` is run to remove the warning about the new version.
Last but not least: `generate-all.sh` introduced a `debug` option. See [README](README.md).
=> feat: improve docker setup

tools/converter.py
When runing the generate tools I noticed:
```text
/colors/tools/converter.py:11: SyntaxWarning: invalid escape sequence '\.'
iterm_re = re.compile("(.+)\.itermcolors$")
```
Since it's a double quoted string I strongly assume it has to be "\\.".
Fixed with this PR.
=> fix: invalid escape sequence in converter.py:11

README.md, tools/preview-generic.sh
Right now `tools/preview.rb` uses iTerm-specific escape codes to preview the theme. This adds a more generic preview script which works in any terminal emulator, using the OSC 4 escape codes. It works by just running the shell scripts in the `preview/` directory, it doesn't do any translation on its own.
Here's a screenshot of it in action:
I left the original `preview.rb` script alone because iTerm's proprietary escape codes support theming more parts of the UI (like the cursor text), so the "generic" preview script doesn't have the exact same behaviour. 
I also moved the "Previewing color themes" TOC link up in the README because I didn't think it made sense for it to be in the middle of the instructions for all the different terminal emulators.
=> Add a preview script that works in more terminal emulators

tools/terminal2iterm.py
This script provides a simple way to convert color themes from the native format used by the Apple Terminal (.terminal) into an iTerm2 compatible format (.itermcolors). It is based on the [iterm2terminal](https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/tools/iterm2terminal.py) script, providing the reverse functionality.
=> Add Terminal to iTerm converter

tools/gen.py
[According to the docs](https://github.com/mbadolato/iTerm2-Color-Schemes/blob/6c7a24bb2e4506f55f7898bf42175be0aa128dd2/yaml/README.md?plain=1#L7-L11), the YAML format is supposed to support the extra `badge` key, but the corresponding YAML-to-iTerm name map was missing. This resulted in an error and the `badge` color not actually being converted to other formats.
=> fix(tools): add missing YAML name map for the `badge` key

tools/preview.rb
`File.exists?` has been deprecated, then removed, in [recent ruby versions](https://github.com/ruby/ruby/blob/d9efc56c16267fabcfc764fd27cf4e464a231a76/doc/NEWS/NEWS-3.2.0.md?plain=1#L589).
Fails with `missing method "exists?"` in the most recent `ruby 3.5.0preview1`, and probably earlier/currently stable versions, as well. In any case, the change to `.exist?` works for anything released since the Obama administration.
thx for your work 🦫,
karl
> [!NOTE]
> timeline for illustrative purposes only; no specific sequencing of _Obama Term 1/  Term 2_ and _iTerm / iTerm2_ is implied.
=> fixes preview.rb's use of renamed ruby method File.exist(s)?

ghostty/catppuccin-frappe, ghostty/catppuccin-macchiato, ghostty/catppuccin-mocha
https://github.com/catppuccin/ghostty/pull/15 fixes a typo in ANSI `color7` and `color15`, and this includes that fix.
Continuation of https://github.com/mbadolato/iTerm2-Color-Schemes/pull/572.
=> fix: sync ghostty catppuccin themes with upstream

ghostty/Atom One Dark, schemes/Atom One Dark.itermcolors
Currently color of cursor text is same with cursor background. This PR fixes that. Background color used for cursor text.
=> Ghostty: fix cursor text not being visible
