tools/iterm2terminal.swift
This is a mix of automatic conversion by XCode and manual changes (mostly arguments handling).
I'm not a Swift developer, but the end result looks fine to me and it works:)
=> Port iterm2terminal.swift to Swift 3

README.md
Changed the wording to be more accurate and bolded link names.
=> Changes to Readme Verbiage & Punctuation

Xresources/Firewatch
=> Add Xresources file for Firewatch theme

README.md
It could be more readable by using the proper markdown heading syntax.
=> Enable markdown heading syntax

README.md
Hi Mark,
Second attempt at pull request. Placed both methods (which really lead to same spot).
Let me know if it makes sense.
Eli
PS: I was thinking of adding an animated gif like the attached one but it's size is rather big.
PSPS: Here's the animated gif for the preference approach (again - probably too bug for page):
=> Updated readme with 2 ways to get to theme change in iTerm

README.md, screenshots/README.md
=> Fix fahrenheit markup

README.md
I initially went to the wrong directory to download the theme I wanted to install.
=> Make link to schemes directory for clarity

README.md
Hi @mbadolato, I added instructions for the Xfce terminal and tested.
=> Update README to include Xfce terminal instructions

tools/screenshotTable.sh
I stumbled upon this script while looking for something similar and got curious about it. It seems like you were wondering who was the original author in #7. This is now documented 🙂
=> Document source of screenshotTable script

index.html
Listen taken from 'README.md'.
This project is awesome, people should know it supports their favorite terminal! 🙂
=> Mention support for all the different terminal types

README.md
I made these changes to the home page only, but I am happy to make PR for the web page as well and anywhere else these parts are being used <span style="text-decoration: underline;">**IF**</span> you guys like the change.
=> Improve clarity of directions

vscode/Mirage.json
I like this for Windows Terminal, so I just created the pendant for VSCode.
=> Mirage theme for VSCode

README.md, tools/update_all.py, tools/xrdb2alacritty.py
Here is a script for creating schemes for the Allacrity terminal. To avoid mess, I will add the schemes themselves as a separate request.
Also it will close #177.
=> Add xrdb-to-alacritty conversion script

index.html
Add missing themes
Fix broken screenshots
Fix mismatched screenshots
Re-alphabetize themes
=> GitHub Pages cleanup

README.md
Also correct `Blueberry_Banana` to `Banana_Blueberry`
=> Add missing images to README

index.html
Correct "Mokokai" to "Monokai". Closes #78
=> Correct typo in credits

tools/genMD.py
Screenshots will now be listed alphabetically
Non `.png` files will be excluded from output
Closes #308
=> Update screenshot README script

tools/genMD.py, tools/xrdb2electerm.py
Add missing line break from screenshots readme
Remove leftover debugging code from electerm converter
=> Code cleanup

index.html
Change wording around non-iTerm installation
=> Update site with missing screenshots

index.html
=> Add Peppermint theme

screenshots/README.md
Use new `genMD` script to generate alphabetized README, adding numerous missing themes.
=> Update screenshots README

index.html
This updates the gh-pages deployed site
=> Add GitHub Dark to jekyll site

tools/iterm2tilda.py, tools/tilda_converter.py, tools/update_all.py
Creates a wrapper around `iterm2tilda.py` and includes it in `update_all.py`.
Closes #319
=> Include Tilda conversion in update_all.py

index.html
Replaced `+` in URLs with `%20`
Closes #292
=> Fix spaces in URLs

tools/iterm2terminal.py
Created a Python converter for iTerm2 to Terminal.app formats.
Closes #305
=> iTerm to Terminal converter

index.html
- Abernathy
- Iceberg
- Matrix and Dark Matrix
=> Add missing themes and credits

index.html
Add missing screenshots and credits to web site
=> Add Alabaster and Darker Matrix themes

README.md
Fix heading level for Dark+ in README
=> Fix heading level

index.html
Fixes the download links for Gruvbox themes.
=> Fix download links for Gruvbox themes

CREDITS.md, README.md
Removed trailing conflict markers.
=> Remove trailing conflict markers in Markdown docs

CREDITS.md
Added full Nord theme credits to CREDITS.md
=> Full credits for Nord themes

Dockerfile, README.md, generate-all.sh
I don't use python un my computer and did not want to install it.
But as a developer I use docker all the time, so I created a `Dockerfile` and a `generate-all.sh` script to do all the manual work of creating the different schemes and screenshots for me.
=> feat: create Dockerfile and a generate-all script to enable easy scheme generation

README.md, requirements.txt, tools/p3tosRGB.py
Tool to convert from P3 color space to sRGB see Issue #539
=> feat: conversion tool from P3 to sRGB

README.md
This small PR fixes two missing screenshot assets.
=> fix screenshot assets

tools/templates/konsole.colorscheme
=> Add console faint, just map ansi 0-7

yaml/Powershell.yml
=> powershell theme

.github/workflows/generate-all.yml
=> add paths ../schemes ../terminal

gh-pages/index.j2
=> update webpage to sort case-insensitive by name

yaml/Gruvbox Material Dark.yml, yaml/Gruvbox Material Light.yml
https://github.com/sainnhe/gruvbox-material/
=> Add Gruvbox Material Dark & Light

yaml/Matte Black.yml
=> Add Matte Black theme from Omarchy

tools/gen.py, tools/wcag_check.py
=> FIX: Add WCAG check and adjustment on cursor text on cursor color.
